# Dockerfile for Nginx to serve the web app
FROM arm64v8/nginx:1.27.2-alpine

# COPY nginx.conf /etc/nginx/nginx.conf

# Copy the static web files to Nginx's default location
COPY ./app /usr/share/nginx/html

# Use a startup script to substitute environment variables
COPY ./entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

# Expose the port for the web server
EXPOSE 80

# Run the entrypoint script that replaces variables and starts Nginx
ENTRYPOINT ["/entrypoint.sh"]
